### PR TITLE
WIP: Migrate to AWS SDK v2

### PR DESCRIPTION
**Pull request by beyhan**
This change mainly contains renaming of the `AWS` namespace to `Aws`.
See migration [guide](https://github.com/aws/aws-sdk-ruby/blob/master/MIGRATING.md). Migration guide is not so helpful.

**General findings:**

* Credentials handling is [different](https://github.com/beyhan/bosh-aws-cpi-release/blob/d5617a928734338ae1ed81cc4c062e260ff3d741/src/bosh_aws_cpi/lib/cloud/aws/cloud.rb#L60) 
* In SDK v2 the default is more request driven, having all actions available on the [`Aws::EC2::Client`](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html). The old 'model way' lives in [`Aws::EC2::Resource`](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Resource.html). In the code the change might look like [this](https://github.com/beyhan/bosh-aws-cpi-release/blob/d5617a928734338ae1ed81cc4c062e260ff3d741/src/bosh_aws_cpi/lib/cloud/aws/cloud.rb#L69).
* `availability_zones`: azs are now attached to `network_interfaces` not to instances. In addition they don't exist as a separate Resource object.
* Elastic Ips: There are now two IP types, [ClassicAddress](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/ClassicAddress.html) and [VpcAddress](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/VpcAddress.html)

[#133654901](https://www.pivotaltracker.com/story/show/133654901)

Signed-off-by: Felix Riegger <felix.riegger@sap.com>

### CODE REVIEW

**Comment by cppforlife** [comment]
@beyhan @voelzmo let us know if you want us to do stuff with it (as it's currently called wip)

**Comment by voelzmo** [comment]
@cppforlife you can pick up from here and decide if the code is actually useful to you. We stopped working on it. See @beyhan's and @friegger's assessment/findings above.

**Comment by cppforlife** [comment]
@voelzmo got it.

**Comment by cppforlife** [comment]
More work happened on master. Promoting sdk v2 soon.

**Pull request closed without merging**
