### PR TITLE
Retry instance#terminate when rate limit exceeded

### PR DESCRIPTION
**Pull request by dcarley**
Wrap instance termination with `Bosh::Common.retryable` so that BOSH waits and
retries if it's unable to terminate an instance due to AWS rate limiting API
requests. This is essentially the same as 2953c67 for instance creation.

The `true` at the end of the block is necessary to stop retries when
`@aws_instance.terminate` hasn't returned any exceptions. This is commented
elsewhere in the codebase, but I feel that a commit message would better
serve as documentation here. The tests will dutifully fail without it.

We have experienced `bosh_cli#delete_deployment` fail quite frequently when
deleting a full Cloud Foundry deployment. It requires a second run to clean
up the inconsistent state afterwards:

      Started deleting instances
      Started deleting instances > clock_global/0
      Started deleting instances > loggregator_trafficcontroller_z1/0
      Started deleting instances > hm9000_z1/0
      Started deleting instances > api_z1/0
      Started deleting instances > uaa_z1/0
      Started deleting instances > nats_z1/0
      Started deleting instances > doppler_z1/0
      Started deleting instances > etcd_z1/0
      Started deleting instances > postgres_z1/0
      Started deleting instances > postgres/0
      Started deleting instances > consul_z1/0
      Started deleting instances > runner_z2/0
      Started deleting instances > runner_z1/0
      Started deleting instances > graphite/0
      Started deleting instances > router_z1/0
      Started deleting instances > nats_z2/0
      Started deleting instances > stats_z1/0
      Started deleting instances > elasticsearch_master_z1/0
       Failed deleting instances > doppler_z1/0: Unknown CPI error 'Unknown' with message 'Rate exceeded' (00:01:27)
       Failed deleting instances > runner_z2/0: Unknown CPI error 'Unknown' with message 'Rate exceeded' (00:01:27)
       Failed deleting instances > clock_global/0: Unknown CPI error 'Unknown' with message 'Rate exceeded' (00:01:27)
         Done deleting instances > loggregator_trafficcontroller_z1/0 (00:02:31)
         Done deleting instances > router_z1/0 (00:02:49)
         Done deleting instances > api_z1/0 (00:03:00)
         Done deleting instances > uaa_z1/0 (00:03:12)
         Done deleting instances > hm9000_z1/0 (00:03:18)
         Done deleting instances > runner_z1/0 (00:03:25)
         Done deleting instances > stats_z1/0 (00:03:25)
         Done deleting instances > nats_z1/0 (00:03:28)
         Done deleting instances > postgres/0 (00:03:43)
         Done deleting instances > graphite/0 (00:04:03)
         Done deleting instances > elasticsearch_master_z1/0 (00:04:06)
         Done deleting instances > postgres_z1/0 (00:04:09)
         Done deleting instances > consul_z1/0 (00:04:12)
         Done deleting instances > etcd_z1/0 (00:04:19)
         Done deleting instances > nats_z2/0 (00:04:57)
       Failed deleting instances (00:04:57)

    Error 100: Unknown CPI error 'Unknown' with message 'Rate exceeded'

### CODE REVIEW

**Comment by cppforlife** [comment]
I wonder if aws sdk allows wrapping of internal client or configuring the library such that all requests are retried if rate limit is met?

**Comment by dcarley** [comment]
Good point, I'll investigate.

**Comment by keymon** [comment]
Related to this, I wonder if setting this [`aws.max_retries`](https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh#p=aws.max_retries) might fix the issue, as it would make the used sdk to retry. (see #19)

**Comment by dcarley** [comment]
Superseded by #23

**Pull request closed without merging**
